### ISSUE TITLE
Use best-practice config as base

### ISSUE THREAD

**Issue by thypon** [brave/renovate-config#2]
https://github.com/renovatebot/renovate/issues/16100

**Comment by thypon** [comment]
https://github.com/renovatebot/renovate/pull/21239/files

**Comment by diracdeltas** [comment]
Would be great to put a delay for updates (ex: 1 week after publish) in case it's malware

**Comment by thypon** [comment]
https://github.com/brave/renovate-config/commit/622e489fd365bdd56d675355cc9379057d7c784c
